Added Post Screen
wwi21seb-projekt/Breta pull request #17
Opened 2024-01-18 15:56 UTC by MarceloEito

## Breta - PR Checkliste

## Code

- [ ] Der Code ist klar und verständlich geschrieben
- [ ] Die Naming Conventions (Variablen, Methoden und Dateinamen in CamelCase) wurde eingehalten
- [ ] Die Namensgebungen sind eindeutig und selbsterklärend
- [ ] Neue Dateien sind in der Ordnerstruktur entsprechend richtig eingeordnet
- [ ] Jede Komponente erfüllt genau eine Funktionalität
- [ ] Codereduzierungen wurden durch die Erstellung neuer Komponenten vermieden
- [ ] Sämtliche Variablen und Rückgabewerte von Methoden sind vollständig typisiert

## Design

- [ ] Die Anwendung sieht auf unterschiedlichen Bildschirmgrößen und -formaten von mobilen Endgeräten gut aus (responsive Design)
- [ ] Die Anwendung funktioniert sowohl auf IOS, als auch auf Android
- [ ] Die Farbgebung deckt sich mit dem festgelegten Theme
- [ ] Falls zusätzlich zu TailwindCSS weitere Styles verwendet werden mussten, wurde dies in einem seperaten Stylesheet (in Stylesheets Directory) gemacht
- [ ] Der Benutzer hat eine klare Navigationsstruktur (z.B. farbliche Markierung auf welchem Tab er ich gerade befindet oder wie er zurücknavigieren kann)
- [ ] Interaktionspunkte (Buttons, Inputs, etc.) sind für den Benutzer klar ersichtlich und leicht zu bedienen

2024-01-18 17:04 UTC, thommy3 requested changes
Allgemein: 
Schau dir auch gerne nochmal die 4 Issues aus Sonar an. Z.B. ungenutztes importiertes Stylesheet, etc.

2024-01-18 17:04 UTC, thommy3 commented on navigation/TabBottomBar.tsx
> +        listeners={({ navigation }) => ({
was macht der listener hier? Den haben wir noch nie benutzt

2024-01-18 17:04 UTC, thommy3 commented on navigation/TabBottomBar.tsx
> -          tabBarShowLabel: false,
hier bitte tabBarShowLabel: false verwenden. Da hst du wahrscheinlich falsch gemerged :)

2024-01-18 17:04 UTC, thommy3 commented on screens/Post.tsx
> +          style={styles.textInput}
style bitte rausnehmen. Nur tailwind

2024-01-18 17:04 UTC, justSchwab commented on screens/Post.tsx
> +        <Text style={{ color: COLORS.black, fontSize: SIZES.small }}>
auch hier wieder style rausnehmen

2024-01-18 17:04 UTC, justSchwab commented on screens/Post.tsx
> +            style={{ color: COLORS.red, paddingTop: 20, textAlign: "center" }}
style rausnehmen

2024-01-18 17:04 UTC, justSchwab commented on screens/Post.tsx
> +          style={[
style...

2024-01-18 17:04 UTC, justSchwab commented on screens/Post.tsx
> +            styles.postButton,
style...

2024-01-18 17:04 UTC, justSchwab commented on screens/Post.tsx
> +          <Text style={{ color: COLORS.black, fontSize: SIZES.small }}>
style

2024-01-18 17:04 UTC, justSchwab commented on stylesheets/styleFloatingInput.ts
>    },
das kannst du alles mit Tailwind machen. Dafür brachst du kein extra Stylesheet. Stylesheets wirlich nur nutzen, wenn Tailwind an seine Grenzen stößt

2024-01-18 17:04 UTC, justSchwab commented on stylesheets/styleFloatingInput.ts
> +  registerButton: {
dafür auch Tailwind nutzen!

2024-01-18 17:04 UTC, justSchwab commented on stylesheets/styleFloatingInput.ts
>    error: {
auch Tailwind und dann hier löschen

2024-01-18 17:04 UTC, justSchwab commented on stylesheets/stylePost.ts
> +import { StyleSheet } from "react-native";
komplettes Stylesheet hier unnötig. Siehe Kommentare oben. Alles direkt mit Tailwind in den Code. Stylesheet danach wieder löschen

2024-01-20 11:56 UTC, Nico1808 requested changes
Die beiden stylesheets müssen auch noch raus laut justins review :)

2024-01-20 11:56 UTC, Nico1808 commented on screens/Post.tsx
> +    axios
Bitte alle Requests mit fetch() und async machen. axios ist unnötig schwergewichtig, dafür dass, wir dessen funktionen eh nicht nutzen

2024-01-20 11:56 UTC, Nico1808 commented on screens/Post.tsx
> +        {!(postError.length === 0) && (
Warum frägst du hier auf die länge des postErrors ab? Kann man das nicht auch mit null oder ähnlichem machen? Oder muss das in React so abgefragt werden? Ich weiß es nicht aber sieht iwie off aus

2024-01-20 11:56 UTC, Nico1808 commented on screens/Post.tsx
> +    axios
für nen beispiel gern im search screen anschauen

2024-01-22 12:15 UTC, Nico1808 commented on screens/Post.tsx
> +        {!(postError.length === 0) && (
Passt so. War nur unwissend :)

2024-01-24 13:57 UTC, justSchwab requested changes

2024-01-24 13:57 UTC, justSchwab commented on navigation/TabBottomBar.tsx
> +        listeners={({ navigation }) => ({
ist geklärt

2024-01-24 13:57 UTC, justSchwab commented on screens/Post.tsx
> +      } catch (error) {
ich glaub ein error tritt hier nur auf, wenn der fetch nicht gelingt. Sobald eine Antwort zurückkommt, ist das kein Error, sondern die response hat den status 400 oder 401, daher hier nochmal entsprechend ändern. Es macht auch Sinn, einen default Wert einzufügen, sollte warum auch immer vom Backend ein anderer Fehlercode zurückkommen

2024-01-24 13:57 UTC, justSchwab commented on screens/Post.tsx
> +          className="flex-1 border-2 mt-10 ml-2.5 mr-2.5 border-[#ccc] rounded-[8px] p-2"
hier bitte den Hexwert rausnehmen und durch einen Farbenwert z.B. lightgray ersetzen

2024-01-24 13:57 UTC, justSchwab commented on stylesheets/styleFloatingInput.ts
>    error: {
hier bitte noch löschen

2024-01-24 13:58 UTC, justSchwab commented on stylesheets/stylePost.ts
> +import { StyleSheet } from "react-native";
bitte noch löschen

2024-01-25 09:52 UTC, Nico1808 approved these changes

2024-01-25 09:55 UTC, thommy3 approved these changes
lgtm

2024-01-25 09:56 UTC, merged