Auth context
wwi21seb-projekt/Breta pull request #26
Opened 2024-02-01 17:42 UTC by MarceloEito

## Breta - PR Checkliste

## Code

- [ ] Der Code ist klar und verständlich geschrieben
- [ ] Die Naming Conventions (Variablen, Methoden und Dateinamen in CamelCase) wurde eingehalten
- [ ] Die Namensgebungen sind eindeutig und selbsterklärend
- [ ] Neue Dateien sind in der Ordnerstruktur entsprechend richtig eingeordnet
- [ ] Jede Komponente erfüllt genau eine Funktionalität
- [ ] Codereduzierungen wurden durch die Erstellung neuer Komponenten vermieden
- [ ] Sämtliche Variablen und Rückgabewerte von Methoden sind vollständig typisiert

## Design

- [ ] Die Anwendung sieht auf unterschiedlichen Bildschirmgrößen und -formaten von mobilen Endgeräten gut aus (responsive Design)
- [ ] Die Anwendung funktioniert sowohl auf IOS, als auch auf Android
- [ ] Die Farbgebung deckt sich mit dem festgelegten Theme
- [ ] Falls zusätzlich zu TailwindCSS weitere Styles verwendet werden mussten, wurde dies in einem seperaten Stylesheet (in Stylesheets Directory) gemacht
- [ ] Der Benutzer hat eine klare Navigationsstruktur (z.B. farbliche Markierung auf welchem Tab er ich gerade befindet oder wie er zurücknavigieren kann)
- [ ] Interaktionspunkte (Buttons, Inputs, etc.) sind für den Benutzer klar ersichtlich und leicht zu bedienen

2024-02-01 19:19 UTC, Nico1808 requested changes

2024-02-01 19:19 UTC, Nico1808 commented on screens/Search.tsx
Wir haben doch gesagt nicht in unseren Code einfügen....

2024-02-01 19:29 UTC, MarceloEito commented on screens/Search.tsx
Ich dachte nur den Authentification Teil im Header?

2024-02-01 19:30 UTC, Nico1808 commented on screens/Search.tsx
ne eben nicht. so wie das file auf main ist, fexistiert es schon lang nimmer. Hab ja gemeint, dass ich des grad noch am umbauen bin :D

2024-02-01 19:36 UTC, MarceloEito commented on screens/Search.tsx
Alright dann wirds natürlich gefixt

2024-02-19 21:07 UTC, Nico1808 approved these changes
useCheckAuthentication() evtl. noch prüfen ob Token schon ausgelaufen ist.
Im Hinterkopf behalten, falls es zu problemen führt.

2024-02-19 21:08 UTC, merged